### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by uo277963** [Arquisoft/dede_en1a#77] opened 2022-03-24 09:10 UTC
Set up the whole deployment pipeline in order to continuously deploy releases onto the AWS cloud.

**Comment by uo277963** [comment] 2022-03-24 11:18
@pglez82 the pipeline is set up, but it stops midway as e2e tests fail. Should we keep the job and comment the failing lines out or remove it completely from the GitHub actions steps?

**Comment by pglez82** [comment] 2022-03-24 12:18
You can comment this job in the yaml. Next session we are going to talk about e2e tests in the lab session so we can configure them there.

**Comment by uo277963** [comment] 2022-03-24 16:33
Thank you @pglez82 , that solved it. However, we now have a different problem. In [this CI run](https://github.com/Arquisoft/dede_en1a/actions/runs/2035058571), you can see the ubuntu server started properly but failed to pull the newly pushed images from ghcr, as it lacked the necessary permissions. I found [this](https://github.com/docker/login-action) docker action which logs in using a token the organization needs to provide, but we lack. Also, our actions are not running on release - no clue why. Any ideas on these two issues?

**Comment by uo277963** [comment] 2022-03-24 16:48
Nevermind the last part, actions fixed themselves. We still cannot retrieve the pushed images though.

**Comment by pglez82** [comment] 2022-03-24 16:56
The problem is that pushed packages are private. I do not know why. The packages that I push to my repository are public:

https://github.com/pglez82?tab=packages&repo_name=asw2122_0

 Let me see I can see the problem.

**Comment by pglez82** [comment] 2022-03-24 17:03
I changed the visibility to both packages (packages, select a docker image, package settings, and Change package visibility).

Now it should work.

**Comment by pglez82** [comment] 2022-03-24 17:04
I suppose the next images that you upload will be public already, though I am not sure. You can confirm it when you test it.

**Comment by uo277963** [comment] 2022-03-24 22:06
Alright, that solved it. There is still a problem when reaching the restapi, but probably solvable.

**Comment by uo277963** [comment] 2022-03-27 11:27
As an update on this issue, the deployment pipeline is working properly: both images are compiled, uploaded to ghcr and deployed on the target machine.

However, the application is not working. While the web app shows fine and is responsive, it fails to connect to the backend rest api and so there are no products listed.
After tracing the problem for a while, I believe this is a problem in the backend server code and not a misconfiguration on the Amazon server or pipeline.

I attach a screenshot of both machines deployed on my machine, where the issue is reproduced.

![image](https://user-images.githubusercontent.com/79209573/160279317-f6a8be0e-6a0f-4fd7-8aa1-129698b5beff.png)

**Comment by uo277963** [comment] 2022-03-28 19:00
I have determined that the cause of the problem is that the RESTAPI_URL parameter is not being properly passed on to the webapp, and so it defaults to sending the requests to localhost:5000.
As the webapp is client-sided, localhost points to the user's computer and the request fails. Otherwise, the rest api is working perfectly and can be requested on the correct port.

**Comment by pglez82** [comment] 2022-03-28 19:17
Can you tell me where is the `RESTAPI_URL` parameter? In which branch are you working?

**Comment by uo277963** [comment] 2022-03-28 19:46
My mistake, I meant API_URI/REACT_APP_API_URI, not RESTAPI_URL (which does not exist). These variables are on webapp/Dockerfile, asw2122.yml and used throughout the app (most noticeably, on webapp/src/helpers/getData.ts).

As for the branch, I'm now working on deployment-arguments.

**Comment by pglez82** [comment] 2022-03-29 06:59
Why have you commented the line: `#RUN npm run build` in the Dockerfile of the webapp?

**Comment by uo277963** [comment] 2022-03-31 10:05
@pglez82 This is still not working, even with the correction. Currently deployed on http://3.89.125.134:3000, if you want to check it out

**Comment by pglez82** [comment] 2022-03-31 13:51
Two things here:

1) No point in using `npm run build` if you then use npm start. It should be npm run prod. Anyway, this is not the error as the variable should be used with npm start anyway

2) `API_URI: http:// ${{ secrets.DEPLOY_HOST }} :5000` should be `API_URI: http://${{ secrets.DEPLOY_HOST }}:5000`.

**Comment by uo277963** [comment] 2022-03-31 15:14
We are working on the first problem right now. I tested just now the change on the second point, and it does not work either.

**Comment by pglez82** [comment] 2022-03-31 16:24
I have checked and problem 1) will not solve the issue. I have tested my deployment and it works with npm start (see the last build in my repository).

I am pretty sure that your dockerfile is correct, there is some problem with the actions. I say this because if I build your webapp docker image manually passing the argument, it works.

If you compare the output of your actions with mine, there is a big difference. Mine:

```Step 6/9 : ARG ***="http://localhost:5000/api"
 ---> Running in 07b83479bf79
Removing intermediate container 07b83479bf79
 ---> 1f7135ffae68
Step 7/9 : ENV REACT_APP_***=$***
 ---> Running in 62fc36e640cf
Removing intermediate container 62fc36e640cf
 ---> 44624707c21c
Step 8/9 : RUN npm run build
```

Yours (taken from build v0.0.3-deploy.6)
```
Step 6/9 : ARG API_URI
 ---> Running in f739d88dd0d4
Removing intermediate container f739d88dd0d4
 ---> 786cb18e4d8f
Step 7/9 : ENV REACT_APP_API_URI=$API_URI
 ---> Running in a2eee5700311
Removing intermediate container a2eee5700311
 ---> 0e961e9e400b
Step 8/9 : RUN npm run build
```

You can see how in my case, it is passing the secret and in your builds, it is not. I will compare my yaml file with yours line by line to spot the problem.

Pablo

**Comment by ludvij** [comment] 2022-03-31 16:25
apparently we needed buildargs in the yml file, now it's working

**Comment by pglez82** [comment] 2022-03-31 16:26
When  I last checked it was there. Maybe you committed that a few minutes ago.

I am glad that it is working.

**Closed** 2022-03-31 16:51 UTC
Labels: enhancement
